# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Finding-Falcone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Finding-Falcone

  # Network
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'Kingfisher'  
  
  # Design
  pod 'RxSwift'
  pod 'RxCocoa'
  
  #Alert
  pod 'SwiftMessages'
    
  # Activity Indicator
  pod 'MBProgressHUD', '1.1.0'

end
